# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ThePerkinrex
email: theperkinrex@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm ThePerkinrex and I mostly develop in Python 3, Java and Arduino but I also know JavaScript(EcmaScript),
  CSS, HTML, Kotlin and processing(A Java based environtment).
  I'm also developing a language called Jiro in Python.
  I have a few projects (the ones shown in this website)
  and some smaller ones open in my github account
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theperkinrex.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  theperkinrex

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/css"
    values:
      style: true
  - scope:
      path: "assets/files"
    values:
      res: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
